---
title: "app"
author: "Group07"
date: "2022-09-04"
output: html_document
---


```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(prettydoc, plotly,DT, lubridate,stats,data.table,readr,dplyr,tidyr,readtext,kableExtra,shinydashboard,shinyjs,shiny,tidyverse)
```


```{r setup, include=FALSE}
final_dataset <- read_csv("Final_dataset_group_07.csv")
```
#basic app
```{r inclued=False,warning = FALSE}
ui <-fluidPage(
  titlePanel("TitlePanel"),
  tabsetPanel(type = "tabs",
              tabPanel("Plot",
                       fluidRow(
                         sidebarLayout(
                           sidebarPanel(
                             selectInput("Gemeinden","Gemeinden: ",c(""),multiple = TRUE),
                             dateRangeInput("daterange","Date range:",start = min(final_dataset$Zulassung),end=max(final_dataset$Zulassung),min = min(final_dataset$Zulassung),max=max(final_dataset$Zulassung))
                             ),
                           mainPanel(
                             plotOutput(outputId ="plot")
                             ),
                           position = "left")
                         )
                       )
              )
  )
             

server <-function(input, output,session) {
  final_dataset <- read_csv("Final_dataset_group_07.csv")
  #base on the input of the user the prompted output changes
  updateSelectInput(session,inputId = "Gemeinden",choices=unique(final_dataset$Gemeinden))
  
  #plot function 
  output$plot <-renderPlot({
    #final_dataset%>%group_by(Gemeiden)%>%summarise(total_sell = sum(`Number of Vehicle`))
    final_dataset%>%filter(Gemeinden %in% input$Gemeinden )%>%filter(Zulassung >= input$daterange[1] & Zulassung <=input$daterange[2] )%>%
      ggplot(aes(x=Zulassung ,y=`Number of Vehicle`,color = Gemeinden))+
      geom_line()
  })
}

shinyApp(ui = ui, server = server)

```


